# Generated by Django 6.0.2 on 2026-03-02 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("token", models.CharField(max_length=500, unique=True)),
                ("device_type", models.CharField(choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")], max_length=20)),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device token",
                "verbose_name_plural": "device tokens",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="devicetoken",
            constraint=models.UniqueConstraint(fields=("user", "token"), name="uniq_device_token_user_token"),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(fields=["user", "is_active"], name="idx_device_user_active"),
        ),
    ]
