# Generated by Django 6.0.2 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="no_show_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_stages_sent",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="appointment",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
