# Generated by Django 6.0.2 on 2026-03-01 00:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('appointment_booking', 'Agendamento de Consultas'), ('notifications_email', 'Notificações por Email'), ('notifications_push', 'Notificações Push'), ('notifications_sms', 'Notificações SMS'), ('marketing', 'Comunicações de Marketing'), ('data_analytics', 'Uso de Dados para Analytics')], max_length=50)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consent record',
                'verbose_name_plural': 'consent records',
                'unique_together': {('user', 'purpose')},
            },
        ),
    ]
