# Generated by Django 6.0.2 on 2026-03-02 00:00

import decimal
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("platform_fee_percentage", models.DecimalField(decimal_places=2, default=decimal.Decimal("10.00"), max_digits=5)),
                ("max_advance_booking_days", models.PositiveIntegerField(default=60)),
                ("min_cancellation_hours", models.PositiveIntegerField(default=24)),
                ("cancellation_fee_percentage", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=5)),
                ("appointment_lock_ttl_minutes", models.PositiveIntegerField(default=10)),
                ("payment_timeout_minutes", models.PositiveIntegerField(default=30)),
                ("max_appointments_per_day_patient", models.PositiveIntegerField(default=3)),
                ("pix_enabled", models.BooleanField(default=True)),
                ("credit_card_enabled", models.BooleanField(default=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "platform setting",
                "verbose_name_plural": "platform settings",
            },
        ),
    ]
