# Generated by Django 6.0.2 on 2026-02-22 14:05

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('weekday', models.IntegerField(help_text='0=Monday, 6=Sunday', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField(default=30, help_text='Slot duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'doctor schedule',
                'verbose_name_plural': 'doctor schedules',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_full_day', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'schedule exception',
                'verbose_name_plural': 'schedule exceptions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('crm', models.CharField(max_length=20)),
                ('crm_state', models.CharField(max_length=2)),
                ('specialty', models.CharField(db_index=True, max_length=100)),
                ('subspecialties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('bio', models.TextField(blank=True)),
                ('consultation_duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('consultation_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='convenios.convenio')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
                'ordering': ['-rating'],
            },
        ),
    ]
