# Generated by Django 6.0.2 on 2026-02-22 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='doctors.doctor'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty', 'is_available'], name='idx_doc_spec_avail'),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('crm', 'crm_state')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'weekday', 'start_time')},
        ),
    ]
