# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
        ("users", "0002_add_consent_record"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS idx_doctor_specialty_trgm "
                "ON doctors_doctor USING gin (specialty gin_trgm_ops);"
            ),
            reverse_sql="DROP INDEX IF EXISTS idx_doctor_specialty_trgm;",
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS idx_user_fullname_trgm "
                "ON users_customuser USING gin (full_name gin_trgm_ops);"
            ),
            reverse_sql="DROP INDEX IF EXISTS idx_user_fullname_trgm;",
        ),
    ]
